// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1mjx27lVt88mPmjrq_y9AR8G1KopRZgA',
    appId: '1:374544286318:web:3720bfae73fcad23a41c7f',
    messagingSenderId: '374544286318',
    projectId: 'neitorsafe',
    authDomain: 'neitorsafe.firebaseapp.com',
    storageBucket: 'neitorsafe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAMtToOwjodxecy0BSYB7UKZ5kjglN5_A',
    appId: '1:374544286318:android:0cee33288572c816a41c7f',
    messagingSenderId: '374544286318',
    projectId: 'neitorsafe',
    storageBucket: 'neitorsafe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCmeDhf0a-BkJbqC1Zt9edK-DuDZbZ_iM',
    appId: '1:374544286318:ios:5602412b7b6b3668a41c7f',
    messagingSenderId: '374544286318',
    projectId: 'neitorsafe',
    storageBucket: 'neitorsafe.appspot.com',
    iosBundleId: 'app.neitor.nseguridad',
  );
}
